version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8888:8080